# -*- coding: utf-8 -*-
"""Dashboard cacao y chontaduro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SuVNZ1_Q9CRrpU7FrRpQ2SUY7UCHpG9d
"""

import pandas as pd

# Cargar archivo CSV
file_path = "Cultivos_permanentes.csv"  # Asegúrate que esté en el mismo repositorio
df = pd.read_csv(file_path)

# Mostrar las primeras filas para confirmar carga
print(df.head())

# Cargar la hoja principal
df = xls.parse('2000-2023')

# Mostrar las primeras filas para examinar la estructura
df.head()

# Filtrar solo los cultivos de interés: cacao y chontaduro
df_filtrado = df[df['Cultivo'].str.lower().isin(['cacao', 'chontaduro'])]

# Agrupar por Año y Cultivo, sumar las métricas relevantes
df_agrupado = df_filtrado.groupby(['Año', 'Cultivo'], as_index=False).agg({
    'Hectareas_sembradas': 'sum',
    'Hectareas_cosechadas': 'sum',
    'Produccion_toneladas': 'sum',
    'Rendimiento_toneladas/hectareas': 'mean'
})

import matplotlib.pyplot as plt

# Crear las gráficas
cultivos = df_agrupado['Cultivo'].unique()
metricas = {
    'Hectareas_sembradas': 'Hectáreas sembradas',
    'Hectareas_cosechadas': 'Hectáreas cosechadas',
    'Produccion_toneladas': 'Producción (toneladas)',
    'Rendimiento_toneladas/hectareas': 'Rendimiento (toneladas/ha)'
}

for metrica, titulo in metricas.items():
    plt.figure(figsize=(10, 5))
    for cultivo in cultivos:
        data = df_agrupado[df_agrupado['Cultivo'] == cultivo]
        plt.plot(data['Año'], data[metrica], marker='o', label=cultivo)
    plt.title(f'{titulo} a través del tiempo')
    plt.xlabel('Año')
    plt.ylabel(titulo)
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()



